### ISSUE TITLE
Python modules 'spotifyapi' or 'fuzzywuzzy' not found.

### ISSUE THREAD

**Issue by marsch2** [tizonia/tizonia-openmax-il#644]
I freshly installed the new tizonia version 0.18.0. on my ubuntu 18 lts but did not manage to get it to play from Spotify.
Using the parameters tizonia --spotify-allow-explicit-tracks --spotify-user <user> --spotify-password <password> --spotify-track-id <url>
I got the following error. I also tried to install these packages manually but no luck there either.
My python3 binding is Python3.6.9 and I installed using:
curl -kL https://github.com/tizonia/tizonia-openmax-il/raw/master/tools/install.sh | bash

Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: No module named spotipy

Python modules 'spotifyapi' or 'fuzzywuzzy' not found.
Please make sure these are installed correctly.

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_source.spotify.pcm:port:0]
 [OMX_ErrorInsufficientResources]

**Comment by tizonia** [comment]
Hi @marsch2 

I've got the impression that you are installing Tizonia on an Arch-based distro?

If that is the case, my suggestion is to wait until the AUR packages have been updated to track the newest version of Tizonia, which is 0.19.0. 

0.18.0 only supported Python 2, which is generally a problem for Arch based distros. The newst Tizonia, 0.19.0, has now support for Python 3.

**Comment by marsch2** [comment]
> Hi @marsch2
> 
> I've got the impression that you are installing Tizonia on an Arch-based distro?
> 
> If that is the case, my suggestion is to wait until the AUR packages have been updated to track the newest version of Tizonia, which is 0.19.0.
> 
> 0.18.0 only supported Python 2, which is generally a problem for Arch based distros. The newst Tizonia, 0.19.0, has now support for Python 3.

I'm actually using Ubuntu 18 and tried the in recommended install script which resulted in this error

**Comment by tizonia** [comment]
Hi @marsch2

Got it. 

Apologies for the confusion. You need to wait a little. What happens is that the new release 0.19.0 was tagged on Friday, but the Debian packages are not yet in Bintray. It takes a few days to create and upload the packages for all the supported distros and architectures (Ubuntu/Debian/Raspbian, amd64 and armhf). I'm working on that as we speak.

I'll ping here when the packages are ready to download. You will just need to re-run the installation script.

**Comment by tizonia** [comment]
Hi @marsch2 

The new packages are now available in the repos. Please re-run the installation script to get the latest version of Tizonia and, more importantly, also the new Python 3 dependencies that are required by 0.19.0.

**Comment by Rkubinski** [comment]
@tizonia @ghost I am having the same issues today, any ideas ?

**Comment by Rkubinski** [comment]
Using python 3.7.3 for reference on Ubuntu 18, could it be anything with this ?

**Comment by peteralexander123** [comment]
Running
`sudo -H pip3 install --upgrade gmusicapi soundcloud youtube-dl pafy pycountry titlecase pychromecast plexapi spotipy fuzzywuzzy eventlet python-Levenshtein`
`sudo -H pip2 install --upgrade gmusicapi soundcloud youtube-dl pafy pycountry titlecase pychromecast plexapi fuzzywuzzy eventlet python-Levenshtein && sudo -H pip2 install git+https://github.com/plamere/spotipy.git --upgrade`
should fix the error. Make sure that pip installs any dependencies because if one of those is unavailable, the others won't be installed either.

**Comment by Rkubinski** [comment]
Hey, still having the same error. I got the pip3 to run but there's a lot of errors for pip2 - plexapi requires python > 3.5 and there are more errors after:
 x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-rrBAp6/python2.7-2.7.17=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c Levenshtein/_levenshtein.c -o build/temp.linux-x86_64-2.7/Levenshtein/_levenshtein.o
  Levenshtein/_levenshtein.c:99:10: fatal error: Python.h: No such file or directory
   #include <Python.h>
            ^~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for python-Levenshtein

regex_2/_regex.c:50:10: fatal error: Python.h: No such file or directory
   #include "Python.h"
            ^~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for regex

Does the python2 install need to occur 100% ? 

Still getting the same error as before when running the following command:

tizonia --spotify-user XXXXXX --spotify-password XXXXXXXXXXX --spotify-allow-explicit-tracks --spotify-track-id https://open.spotify.com/track/18ZCClAxetH4DmqnR0IUXG

Python modules 'spotifyapi' or 'fuzzywuzzy' not found.
Please make sure these are installed correctly.

It's probably an error with python2 then ?

**Comment by Rkubinski** [comment]
follow up - installed plexapi 4.0.0 and still the same issue

**Comment by peteralexander123** [comment]
Does
`sudo -H pip2 install --upgrade gmusicapi soundcloud youtube-dl pafy pycountry titlecase pychromecast fuzzywuzzy eventlet python-Levenshtein && sudo -H pip2 install git+https://github.com/plamere/spotipy.git --upgrade`
or 
`python2 -m pip install --upgrade gmusicapi soundcloud youtube-dl pafy pycountry titlecase pychromecast fuzzywuzzy eventlet python-Levenshtein && python2 -m pip install git+https://github.com/plamere/spotipy.git --upgrade`
(without plexapi) work?

**Comment by Rkubinski** [comment]
both of them work, but theres still the same error as original

**Comment by juanrubio** [comment]
@Rkubinski  / @peteralexander123 

Tizonia nowdays uses Python 3 so the command that you need to use to upgrade Tizonia's Python dependencies goes more or less like this:

```
sudo -H pip3 install gmusicapi soundcloud youtube-dl pafy pycountry titlecase pychromecast plexapi spotipy fuzzywuzzy eventlet python-Levenshtein joblib --upgrade
```

If after issuing this, you still see the `'spotifyapi' or 'fuzzywuzzy' not found.` message, it probably means you have an issue with the Python installation on your system.
